version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    cooldown:
      default-days: 7
